[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",    
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",        
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
